# Generated by Django 5.0.4 on 2024-05-26 15:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_disease_fish_age_fish_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='symptom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('farmer', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('disease_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.disease')),
                ('fish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fish')),
            ],
        ),
    ]
