# Generated by Django 5.0.4 on 2024-05-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_disease_symptom_disease_treatment_harvest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='disease_id',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='harvest',
            old_name='fish_id',
            new_name='fish',
        ),
    ]
