# Generated by Django 5.0.4 on 2024-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_disease_id_harvest_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='date',
            field=models.DateField(),
        ),
    ]
